### ISSUE TITLE
how to update Firmware with no wifi?

### ISSUE THREAD

**Issue by peterus** [CircuitMess/CircuitMess-Ringo-firmware#10]
Hi! i am trying to update the firmware, but when i try to update it over wifi it is giving me an error (-2 -> server error).
Can i trigger the firmware update with the SD card or with the arduino IDE?
for the arduino IDE i am expecting an ino file which is not present.

**Comment by robbie8-bit** [comment]
Hello,

There are a few ways to update the firmware.

1) Using Arduino IDE - it's explained how to do it here https://github.com/CircuitMess/CircuitMess-Ringo/blob/boardArduino/Installation.md

2) Using our IDE CircuitBlocks - You can download it here https://github.com/CircuitMess/CircuitBlocks/releases/
And learn how to do it here https://www.circuitmess.com/circuitblocks-tutorial

3) Directly using the phone - **Go to Settings -> About & Update -> Check for Update**

If this one over the phone is not working for some reason, the other two should do the job.

Robert

**Comment by peterus** [comment]
Hi Robert!

Thank you for pointing to the install readme. I have not seen point 12. in the readme when i first looked at it. now it is clear to me.

Peter
