### ISSUE TITLE
How to edit the home screen 

### ISSUE THREAD

**Issue by jarno9981** [CircuitMess/CircuitMess-Ringo-firmware#19]
How do you edit the home screen which file?

**Comment by filipbudisa** [comment]
Hey, jarno. If you mean the lock screen or the screen that appears when the home button is pushed in a game, that is both in the [CircuitMess-Ringo library](https://github.com/CircuitMess/CircuitMess-Ringo), file src/MAKERphone.cpp.
If you mean the main menu screen, that is in this repo, file src/mainMenu.cpp

Filip
